export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as Security } from './Security';
export { default as About } from './About';
export { default as Stats } from './Stats';
export { default as Booking } from './Booking';
export { default as Diagnostic } from './Diagnostic';
export { default as ChatAssistant } from './ChatAssistant';
export { default as CaseStudy } from './CaseStudy';
